### ISSUE TITLE
Alembic >= 1.13.0 has dropped support for Python 3.7

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/alembic-feedstock#86]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This project indicates that Python 3.7 is still supported.  However, as noted [upstream](https://github.com/sqlalchemy/alembic/blob/rel_1_13_0/setup.cfg), Python 3.8 has been the minimum required version since alembic v1.13.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by xylar** [comment]
@DManowitz, thanks for pointing that out.  I doubt it is particularly important since most conda-forge packages have stopped supporting python 3.7 for a long time now.  Has this caused you trouble?

I also understand how I missed it and will try to do a better job at catching cases like these in the future.
